//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHampson.Gta3CarGenEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHampson.Gta3CarGenEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone.
        /// </summary>
        public static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thehambone93@gmail.com.
        /// </summary>
        public static string AppAuthorContact {
            get {
                return ResourceManager.GetString("AppAuthorContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2018 W. Hampson. All rights reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool allows you to edit the parked car generators in a GTA3 savegame. You can control the car that spawns, it&apos;s location, color, and more! You can also transfer parked car generators between saves on any platform..
        /// </summary>
        public static string AppDescriptionLong {
            get {
                return ResourceManager.GetString("AppDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple tool for editing parked car generators in a GTA3 savegame..
        /// </summary>
        public static string AppDescriptionShort {
            get {
                return ResourceManager.GetString("AppDescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA3 Parked Car Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to GTAKid667 for providing feedback and support during development..
        /// </summary>
        public static string AppSpecialThanks {
            get {
                return ResourceManager.GetString("AppSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ButtonTextCancel {
            get {
                return ResourceManager.GetString("ButtonTextCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string ButtonTextClose {
            get {
                return ResourceManager.GetString("ButtonTextClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string ButtonTextOk {
            get {
                return ResourceManager.GetString("ButtonTextOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Chance.
        /// </summary>
        public static string ColumnHeaderAlarmChance {
            get {
                return ResourceManager.GetString("ColumnHeaderAlarmChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can Spawn.
        /// </summary>
        public static string ColumnHeaderCanSpawn {
            get {
                return ResourceManager.GetString("ColumnHeaderCanSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 1.
        /// </summary>
        public static string ColumnHeaderColor1 {
            get {
                return ResourceManager.GetString("ColumnHeaderColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color 2.
        /// </summary>
        public static string ColumnHeaderColor2 {
            get {
                return ResourceManager.GetString("ColumnHeaderColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force Spawn.
        /// </summary>
        public static string ColumnHeaderForceSpawn {
            get {
                return ResourceManager.GetString("ColumnHeaderForceSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading.
        /// </summary>
        public static string ColumnHeaderHeading {
            get {
                return ResourceManager.GetString("ColumnHeaderHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string ColumnHeaderLocation {
            get {
                return ResourceManager.GetString("ColumnHeaderLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked Chance.
        /// </summary>
        public static string ColumnHeaderLockedChance {
            get {
                return ResourceManager.GetString("ColumnHeaderLockedChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Spawn Delay.
        /// </summary>
        public static string ColumnHeaderMaxSpawnDelay {
            get {
                return ResourceManager.GetString("ColumnHeaderMaxSpawnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min. Spawn Delay.
        /// </summary>
        public static string ColumnHeaderMinSpawnDelay {
            get {
                return ResourceManager.GetString("ColumnHeaderMinSpawnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string ColumnHeaderModelId {
            get {
                return ResourceManager.GetString("ColumnHeaderModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recently Stolen.
        /// </summary>
        public static string ColumnHeaderRecentlyStolen {
            get {
                return ResourceManager.GetString("ColumnHeaderRecentlyStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer.
        /// </summary>
        public static string ColumnHeaderTimer {
            get {
                return ResourceManager.GetString("ColumnHeaderTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown24.
        /// </summary>
        public static string ColumnHeaderUnknown24 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown2C.
        /// </summary>
        public static string ColumnHeaderUnknown2C {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown2C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown30.
        /// </summary>
        public static string ColumnHeaderUnknown30 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown34.
        /// </summary>
        public static string ColumnHeaderUnknown34 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown38.
        /// </summary>
        public static string ColumnHeaderUnknown38 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown3C.
        /// </summary>
        public static string ColumnHeaderUnknown3C {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown3C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown40.
        /// </summary>
        public static string ColumnHeaderUnknown40 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown44.
        /// </summary>
        public static string ColumnHeaderUnknown44 {
            get {
                return ResourceManager.GetString("ColumnHeaderUnknown44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to export the current set of parked cars to. The parked car generators in that file will be overwritten..
        /// </summary>
        public static string DialogMessageExportInfo {
            get {
                return ResourceManager.GetString("DialogMessageExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked cars exported successfully!.
        /// </summary>
        public static string DialogMessageExportSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to import parked cars from. The current set of parked car generators will be overwritten..
        /// </summary>
        public static string DialogMessageImportInfo {
            get {
                return ResourceManager.GetString("DialogMessageImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of parked car generators imported exceeds the maximum amount by {0}. The extra car generators will be omitted..
        /// </summary>
        public static string DialogMessageImportLimitExceeded {
            get {
                return ResourceManager.GetString("DialogMessageImportLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked cars imported successfully!.
        /// </summary>
        public static string DialogMessageImportSuccessful {
            get {
                return ResourceManager.GetString("DialogMessageImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string DialogMessageSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogMessageSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal exception has occurred. The application will be terminated..
        /// </summary>
        public static string DialogMessageUnhandledException1 {
            get {
                return ResourceManager.GetString("DialogMessageUnhandledException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact {0} about this error..
        /// </summary>
        public static string DialogMessageUnhandledException2 {
            get {
                return ResourceManager.GetString("DialogMessageUnhandledException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string DialogTitleAbout {
            get {
                return ResourceManager.GetString("DialogTitleAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string DialogTitleError {
            get {
                return ResourceManager.GetString("DialogTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Parked Cars.
        /// </summary>
        public static string DialogTitleExportInfo {
            get {
                return ResourceManager.GetString("DialogTitleExportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Parked Cars.
        /// </summary>
        public static string DialogTitleImportInfo {
            get {
                return ResourceManager.GetString("DialogTitleImportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Limit Exceeded.
        /// </summary>
        public static string DialogTitleImportLimitExceeded {
            get {
                return ResourceManager.GetString("DialogTitleImportLimitExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string DialogTitleOpenFile {
            get {
                return ResourceManager.GetString("DialogTitleOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string DialogTitleSaveChangesPrompt {
            get {
                return ResourceManager.GetString("DialogTitleSaveChangesPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string DialogTitleSaveFileAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string DialogTitleSuccess {
            get {
                return ResourceManager.GetString("DialogTitleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string DialogTitleUnhandledException {
            get {
                return ResourceManager.GetString("DialogTitleUnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ExceptionMessageConvertBackNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMessageConvertBackNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block size read..
        /// </summary>
        public static string ExceptionMessageIncorrectBlockSizeRead {
            get {
                return ResourceManager.GetString("ExceptionMessageIncorrectBlockSizeRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of bytes decoded..
        /// </summary>
        public static string ExceptionMessageIncorrectNumberOfBytesDecoded {
            get {
                return ResourceManager.GetString("ExceptionMessageIncorrectNumberOfBytesDecoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of bytes encoded..
        /// </summary>
        public static string ExceptionMessageIncorrectNumberOfBytesEncoded {
            get {
                return ResourceManager.GetString("ExceptionMessageIncorrectNumberOfBytesEncoded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expected &apos;{1}&apos;..
        /// </summary>
        public static string ExceptionMessageInvalidBlockTag {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidBlockTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of columns read..
        /// </summary>
        public static string ExceptionMessageInvalidColumnCount {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidColumnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid GTA3 save data file..
        /// </summary>
        public static string ExceptionMessageInvalidFile {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vehicle model ID ({0})..
        /// </summary>
        public static string ExceptionMessageInvalidModelId {
            get {
                return ResourceManager.GetString("ExceptionMessageInvalidModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls are not supported..
        /// </summary>
        public static string ExceptionMessageMultipleCallsNotSupported {
            get {
                return ResourceManager.GetString("ExceptionMessageMultipleCallsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string ExceptionMessageOops {
            get {
                return ResourceManager.GetString("ExceptionMessageOops", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (comma-delimited) (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        public static string FilterCsv {
            get {
                return ResourceManager.GetString("FilterCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA3 Save Data (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FilterGta3SaveData {
            get {
                return ResourceManager.GetString("FilterGta3SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate if player is close counter:.
        /// </summary>
        public static string LabelGenerateIfCloseCounter {
            get {
                return ResourceManager.GetString("LabelGenerateIfCloseCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of active car generators:.
        /// </summary>
        public static string LabelNumberOfActiveCarGenerators {
            get {
                return ResourceManager.GetString("LabelNumberOfActiveCarGenerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of car generators:.
        /// </summary>
        public static string LabelNumberOfCarGenerators {
            get {
                return ResourceManager.GetString("LabelNumberOfCarGenerators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process counter:.
        /// </summary>
        public static string LabelProcessCounter {
            get {
                return ResourceManager.GetString("LabelProcessCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuHeaderEdit {
            get {
                return ResourceManager.GetString("MenuHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHeaderHelp {
            get {
                return ResourceManager.GetString("MenuHeaderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuHeaderView {
            get {
                return ResourceManager.GetString("MenuHeaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuItemHeaderAbout {
            get {
                return ResourceManager.GetString("MenuItemHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked Cars from _CSV....
        /// </summary>
        public static string MenuItemHeaderCarGensFromCsv {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensFromCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked Cars from GTA3 _Save....
        /// </summary>
        public static string MenuItemHeaderCarGensFromSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensFromSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked Cars to _CSV....
        /// </summary>
        public static string MenuItemHeaderCarGensToCsv {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parked Cars to GTA3 _Save....
        /// </summary>
        public static string MenuItemHeaderCarGensToSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _Updates.
        /// </summary>
        public static string MenuItemHeaderCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuItemHeaderCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuItemHeaderClose {
            get {
                return ResourceManager.GetString("MenuItemHeaderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Metadata....
        /// </summary>
        public static string MenuItemHeaderEditMetadata {
            get {
                return ResourceManager.GetString("MenuItemHeaderEditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItemHeaderExit {
            get {
                return ResourceManager.GetString("MenuItemHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string MenuItemHeaderExport {
            get {
                return ResourceManager.GetString("MenuItemHeaderExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string MenuItemHeaderImport {
            get {
                return ResourceManager.GetString("MenuItemHeaderImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuItemHeaderOpen {
            get {
                return ResourceManager.GetString("MenuItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Row Order.
        /// </summary>
        public static string MenuItemHeaderResetRowOrder {
            get {
                return ResourceManager.GetString("MenuItemHeaderResetRowOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuItemHeaderSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuItemHeaderSaveAs {
            get {
                return ResourceManager.GetString("MenuItemHeaderSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Unused Fields.
        /// </summary>
        public static string MenuItemHeaderShowUnusedFields {
            get {
                return ResourceManager.GetString("MenuItemHeaderShowUnusedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zero Out Timers.
        /// </summary>
        public static string MenuItemHeaderZeroOutTImers {
            get {
                return ResourceManager.GetString("MenuItemHeaderZeroOutTImers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported parked cars to {0}..
        /// </summary>
        public static string StatusMessageExportSuccessful {
            get {
                return ResourceManager.GetString("StatusMessageExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export parked cars!.
        /// </summary>
        public static string StatusMessageExportUnsuccessful {
            get {
                return ResourceManager.GetString("StatusMessageExportUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opened for edit..
        /// </summary>
        public static string StatusMessageFileOpened {
            get {
                return ResourceManager.GetString("StatusMessageFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported parked cars from {0}..
        /// </summary>
        public static string StatusMessageImportSuccessful {
            get {
                return ResourceManager.GetString("StatusMessageImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import parked cars!.
        /// </summary>
        public static string StatusMessageImportUnsuccessful {
            get {
                return ResourceManager.GetString("StatusMessageImportUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file opened..
        /// </summary>
        public static string StatusMessageNoFileOpened {
            get {
                return ResourceManager.GetString("StatusMessageNoFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully..
        /// </summary>
        public static string StatusMessageSaveSuccessful {
            get {
                return ResourceManager.GetString("StatusMessageSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file!.
        /// </summary>
        public static string StatusMessageSaveUnsuccessful {
            get {
                return ResourceManager.GetString("StatusMessageSaveUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by:.
        /// </summary>
        public static string TextCreatedBy {
            get {
                return ResourceManager.GetString("TextCreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enjoy my work and would like to help me make more programs in the future, please feel free to make a donation!.
        /// </summary>
        public static string TextDonate {
            get {
                return ResourceManager.GetString("TextDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified.
        /// </summary>
        public static string TextFileModified {
            get {
                return ResourceManager.GetString("TextFileModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string TextVersion {
            get {
                return ResourceManager.GetString("TextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not available).
        /// </summary>
        public static string TextVersionError {
            get {
                return ResourceManager.GetString("TextVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (build {1}).
        /// </summary>
        public static string TextVersionFormat {
            get {
                return ResourceManager.GetString("TextVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability that the vehicle will spawn with an alarm (percentage)..
        /// </summary>
        public static string ToolTipAlarmChance {
            get {
                return ResourceManager.GetString("ToolTipAlarmChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifies whether the vehicle will spawn in the game world, effectively enabling or disabling the parked car generator..
        /// </summary>
        public static string ToolTipCanSpawn {
            get {
                return ResourceManager.GetString("ToolTipCanSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s primary color.
        ///Use -1 for a random color. See carcols.dat for color definitions..
        /// </summary>
        public static string ToolTipColor1 {
            get {
                return ResourceManager.GetString("ToolTipColor1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s secondary color.
        ///Use -1 for a random color. See carcols.dat for color definitions..
        /// </summary>
        public static string ToolTipColor2 {
            get {
                return ResourceManager.GetString("ToolTipColor2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to make a donation with PayPal..
        /// </summary>
        public static string ToolTipDonate {
            get {
                return ResourceManager.GetString("ToolTipDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forces the vehicle to spawn more readily.
        ///It is unclear whether this field has any effect in-game..
        /// </summary>
        public static string ToolTipForceSpawn {
            get {
                return ResourceManager.GetString("ToolTipForceSpawn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s spawn direction in degrees.
        ///0 degrees is due north..
        /// </summary>
        public static string ToolTipHeading {
            get {
                return ResourceManager.GetString("ToolTipHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle&apos;s location in the game world..
        /// </summary>
        public static string ToolTipLocation {
            get {
                return ResourceManager.GetString("ToolTipLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probability that the vehicle will spawn with locked doors (percentage)..
        /// </summary>
        public static string ToolTipLockedChance {
            get {
                return ResourceManager.GetString("ToolTipLockedChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum time to wait before respawning the vehicle after it has been stolen.
        ///Setting this field has no effect as the game always waits 60000ms before re-spawning the vehicle..
        /// </summary>
        public static string ToolTipMaxSpawnDelay {
            get {
                return ResourceManager.GetString("ToolTipMaxSpawnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum time to wait before respawning the vehicle after it has been stolen.
        ///Setting this field has no effect as the game always waits 60000ms before re-spawning the vehicle..
        /// </summary>
        public static string ToolTipMinSpawnDelay {
            get {
                return ResourceManager.GetString("ToolTipMinSpawnDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The vehicle to spawn.
        ///Be warned that certain vehicles (e.g. Airtrain) will crash the game when spawned..
        /// </summary>
        public static string ToolTipModelId {
            get {
                return ResourceManager.GetString("ToolTipModelId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates whether the vehicle has been stolen in the last 60 seconds and is waiting to re-spawn.
        ///Setting this field has no effect..
        /// </summary>
        public static string ToolTipRecentlyStolen {
            get {
                return ResourceManager.GetString("ToolTipRecentlyStolen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game timer when the car is generated.
        ///If the vehicle is not spawning, try setting this to 0..
        /// </summary>
        public static string ToolTipTimer {
            get {
                return ResourceManager.GetString("ToolTipTimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The purpose of this field is unknown and changing it appears to have no effect on the parked car generator..
        /// </summary>
        public static string ToolTipUnknown {
            get {
                return ResourceManager.GetString("ToolTipUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://gtaforums.com/profile/907241-thehambone/.
        /// </summary>
        public static string UrlAuthor {
            get {
                return ResourceManager.GetString("UrlAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://www.paypal.com/cgi-bin/webscr?cmd=_donations&amp;business=KCLQ9SDXKDAHG&amp;lc=US&amp;item_name=Software%20Development%20Donation%20Bucket&amp;currency_code=USD&amp;bn=PP%2dDonationsBF%3abtn_donate_SM%2egif%3aNonHosted.
        /// </summary>
        public static string UrlDonate {
            get {
                return ResourceManager.GetString("UrlDonate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Metadata.
        /// </summary>
        public static string WindowTitleEditMetadata {
            get {
                return ResourceManager.GetString("WindowTitleEditMetadata", resourceCulture);
            }
        }
    }
}
