//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WHampson.Gta3CarGenEditor.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WHampson.Gta3CarGenEditor.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutDialogTitle {
            get {
                return ResourceManager.GetString("AboutDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created by W. Hampson (a.k.a. thehambone).
        /// </summary>
        public static string AppAuthor {
            get {
                return ResourceManager.GetString("AppAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (C) 2018 W. Hampson. All rights reserved..
        /// </summary>
        public static string AppCopyright {
            get {
                return ResourceManager.GetString("AppCopyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool allows you to edit the parked car generators in a GTA3 savegame. You can control the car that spawns, it&apos;s location, color, and more! You can also transfer car generators between saves on any platform..
        /// </summary>
        public static string AppDescriptionLong {
            get {
                return ResourceManager.GetString("AppDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A simple tool for editing parked car generators in a GTA3 savegame..
        /// </summary>
        public static string AppDescriptionShort {
            get {
                return ResourceManager.GetString("AppDescriptionShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA3 Car Generator Editor.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks to GTAKid667 for providing feedback and support during development..
        /// </summary>
        public static string AppSpecialThanks {
            get {
                return ResourceManager.GetString("AppSpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        public static string AppVersion {
            get {
                return ResourceManager.GetString("AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not available).
        /// </summary>
        public static string AppVersionError {
            get {
                return ResourceManager.GetString("AppVersionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (build {1}).
        /// </summary>
        public static string AppVersionFormat {
            get {
                return ResourceManager.GetString("AppVersionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConvertBack is not supported for this converter..
        /// </summary>
        public static string ConvertBackNotSupportedMessage {
            get {
                return ResourceManager.GetString("ConvertBackNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open....
        /// </summary>
        public static string DialogTitleOpenFile {
            get {
                return ResourceManager.GetString("DialogTitleOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As....
        /// </summary>
        public static string DialogTitleSaveFileAs {
            get {
                return ResourceManager.GetString("DialogTitleSaveFileAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to export the current set of car generators to. The car generators in that file will be overwritten..
        /// </summary>
        public static string ExportInfoDialogMessage {
            get {
                return ResourceManager.GetString("ExportInfoDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Car Generators.
        /// </summary>
        public static string ExportInfoDialogTitle {
            get {
                return ResourceManager.GetString("ExportInfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car generators exported successfully!.
        /// </summary>
        public static string ExportSuccessDialogMessage {
            get {
                return ResourceManager.GetString("ExportSuccessDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV (comma-delimited) (*.csv)|*.csv|All Files (*.*)|*.*.
        /// </summary>
        public static string FilterCsv {
            get {
                return ResourceManager.GetString("FilterCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GTA3 Save Data (*.b)|*.b|All Files (*.*)|*.*.
        /// </summary>
        public static string FilterGta3SaveData {
            get {
                return ResourceManager.GetString("FilterGta3SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the file you want to import car generators from. The current set of car generators will be overwritten..
        /// </summary>
        public static string ImportInfoDialogMessage {
            get {
                return ResourceManager.GetString("ImportInfoDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Car Generators.
        /// </summary>
        public static string ImportInfoDialogTitle {
            get {
                return ResourceManager.GetString("ImportInfoDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of car generators imported exceeds the maximum amount by {0}. The extra car generators will be omitted..
        /// </summary>
        public static string ImportLimitExceededDialogMessage {
            get {
                return ResourceManager.GetString("ImportLimitExceededDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Limit Exceeded.
        /// </summary>
        public static string ImportLimitExceededDialogTitle {
            get {
                return ResourceManager.GetString("ImportLimitExceededDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car generators imported successfully!.
        /// </summary>
        public static string ImportSuccessDialogMessage {
            get {
                return ResourceManager.GetString("ImportSuccessDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block size read..
        /// </summary>
        public static string IncorrectBlockSizeReadMessage {
            get {
                return ResourceManager.GetString("IncorrectBlockSizeReadMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of bytes decoded..
        /// </summary>
        public static string IncorrectNumberOfBytesDecodedMessage {
            get {
                return ResourceManager.GetString("IncorrectNumberOfBytesDecodedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of bytes encoded..
        /// </summary>
        public static string IncorrectNumberOfBytesEncodedMessage {
            get {
                return ResourceManager.GetString("IncorrectNumberOfBytesEncodedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect block tag - &apos;{0}&apos;. Expecting &apos;{1}&apos;..
        /// </summary>
        public static string InvalidBlockTagMessage {
            get {
                return ResourceManager.GetString("InvalidBlockTagMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect number of columns read..
        /// </summary>
        public static string InvalidColumnCountMessage {
            get {
                return ResourceManager.GetString("InvalidColumnCountMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid GTA3 save data file..
        /// </summary>
        public static string InvalidFileMessage {
            get {
                return ResourceManager.GetString("InvalidFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid vehicle model ID ({0})..
        /// </summary>
        public static string InvalidModelIdMessage {
            get {
                return ResourceManager.GetString("InvalidModelIdMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string MenuHeaderEdit {
            get {
                return ResourceManager.GetString("MenuHeaderEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string MenuHeaderFile {
            get {
                return ResourceManager.GetString("MenuHeaderFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        public static string MenuHeaderHelp {
            get {
                return ResourceManager.GetString("MenuHeaderHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _View.
        /// </summary>
        public static string MenuHeaderView {
            get {
                return ResourceManager.GetString("MenuHeaderView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _About.
        /// </summary>
        public static string MenuItemHeaderAbout {
            get {
                return ResourceManager.GetString("MenuItemHeaderAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Generators from _CSV....
        /// </summary>
        public static string MenuItemHeaderCarGensFromCsv {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensFromCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Generators from GTA3 _Save....
        /// </summary>
        public static string MenuItemHeaderCarGensFromSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensFromSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Generators to _CSV....
        /// </summary>
        public static string MenuItemHeaderCarGensToCsv {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensToCsv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Car Generators to GTA3 _Save....
        /// </summary>
        public static string MenuItemHeaderCarGensToSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderCarGensToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for _Updates.
        /// </summary>
        public static string MenuItemHeaderCheckForUpdates {
            get {
                return ResourceManager.GetString("MenuItemHeaderCheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Close.
        /// </summary>
        public static string MenuItemHeaderClose {
            get {
                return ResourceManager.GetString("MenuItemHeaderClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit _Metadata....
        /// </summary>
        public static string MenuItemHeaderEditMetadata {
            get {
                return ResourceManager.GetString("MenuItemHeaderEditMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E_xit.
        /// </summary>
        public static string MenuItemHeaderExit {
            get {
                return ResourceManager.GetString("MenuItemHeaderExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export.
        /// </summary>
        public static string MenuItemHeaderExport {
            get {
                return ResourceManager.GetString("MenuItemHeaderExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import.
        /// </summary>
        public static string MenuItemHeaderImport {
            get {
                return ResourceManager.GetString("MenuItemHeaderImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open....
        /// </summary>
        public static string MenuItemHeaderOpen {
            get {
                return ResourceManager.GetString("MenuItemHeaderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Reset Row Order.
        /// </summary>
        public static string MenuItemHeaderResetRowOrder {
            get {
                return ResourceManager.GetString("MenuItemHeaderResetRowOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string MenuItemHeaderSave {
            get {
                return ResourceManager.GetString("MenuItemHeaderSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save _As....
        /// </summary>
        public static string MenuItemHeaderSaveAs {
            get {
                return ResourceManager.GetString("MenuItemHeaderSaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _Unused Fields.
        /// </summary>
        public static string MenuItemHeaderShowUnusedFields {
            get {
                return ResourceManager.GetString("MenuItemHeaderShowUnusedFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Zero Out Timers.
        /// </summary>
        public static string MenuItemHeaderZeroOutTImers {
            get {
                return ResourceManager.GetString("MenuItemHeaderZeroOutTImers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple calls are not supported..
        /// </summary>
        public static string MultipleCallsNotSupportedMessage {
            get {
                return ResourceManager.GetString("MultipleCallsNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You weren&apos;t supposed to be able to get here, you know..
        /// </summary>
        public static string OopsMessage {
            get {
                return ResourceManager.GetString("OopsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your changes?.
        /// </summary>
        public static string SaveChangesPromptDialogMessage {
            get {
                return ResourceManager.GetString("SaveChangesPromptDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes?.
        /// </summary>
        public static string SaveChangesPromptDialogTitle {
            get {
                return ResourceManager.GetString("SaveChangesPromptDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exported car generators to {0}..
        /// </summary>
        public static string StatusExportSuccessful {
            get {
                return ResourceManager.GetString("StatusExportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export car generators!.
        /// </summary>
        public static string StatusExportUnsuccessful {
            get {
                return ResourceManager.GetString("StatusExportUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File opened for edit..
        /// </summary>
        public static string StatusFileOpened {
            get {
                return ResourceManager.GetString("StatusFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imported car generators from {0}..
        /// </summary>
        public static string StatusImportSuccessful {
            get {
                return ResourceManager.GetString("StatusImportSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import car generators!.
        /// </summary>
        public static string StatusImportUnsuccessful {
            get {
                return ResourceManager.GetString("StatusImportUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file opened..
        /// </summary>
        public static string StatusNoFileOpened {
            get {
                return ResourceManager.GetString("StatusNoFileOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved successfully..
        /// </summary>
        public static string StatusSaveSuccessful {
            get {
                return ResourceManager.GetString("StatusSaveSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to save file!.
        /// </summary>
        public static string StatusSaveUnsuccessful {
            get {
                return ResourceManager.GetString("StatusSaveUnsuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string SuccesDialogTitle {
            get {
                return ResourceManager.GetString("SuccesDialogTitle", resourceCulture);
            }
        }
    }
}
